# Portugol

//Faça um programa que leia as duas notas de um aluno em uma matéria e mostre
//na tela a sua média na disciplina.
//Ex:
//Nota 1: 4.5
//Nota 2: 8.5
//A média entre 4.5 e 8.5 é igual a 6.5

Algoritmo "MATEMATICA"

Var

   NA, NB, M: Real

Inicio

      Escreva ("Nota 1: ", NA)
      Leia (NA)
      Escreva ("Nota 2", NB)
      Leia (NB)
      M <- (NA+NB)/2
      Escreva("A media entre",NA, " e",NB, " ï¿½ igual a" ,M)



   

Fimalgoritmo