Algoritmo "semnome"
Var


   N,NN: Inteiro


Inicio

      EscrevaL("Numero 1: ")
      Leia (N)
      EscrevaL("Numero 2: ")
      Leia (NN)

      Se (N > NN) entao
         Escreva ("O primeiro numero é maior")
      Senao
           Se (N < NN) entao
           Escreva ("O segundo numero é maior")
           Senao
           Escreva ("Os dois numero são iguais")
        Fimse
      Fimse


Fimalgoritmo


