Algoritmo "semnome"
//Faça um programa que leia 7 números inteiros e no final mostre o somatório
//entre eles.
Var

       Cont,S,N: Inteiro
Inicio

      Cont <-1
      S <-0

      Enquanto (Cont <= 5) faca
      Escreva ("Digite o", cont," o. valor: ")
      Leia (N)
      S <- S + N
      Cont <- Cont + 1
      Fimenquanto
      EscrevaL ("A Soma de todos os valores foi", S)
      


Fimalgoritmo