
Algoritmo "semnome"

//Escreva um programa que mostre na tela a seguinte contagem:
//6 7 8 9 10 11 Acabou!

Var

   contador,valor: inteiro
  
  
  
Inicio

EscrevaL ("Até que valor deseja contar?" )
Leia (Valor)

 contador <- 0
 Enquanto (contador <= valor) faca
          Escreva (contador)
          contador <- contador + 1
 Fimenquanto
          EscrevaL (" Terminei de contar!")



Fimalgoritmo


