Algoritmo "semnome"
//Crie um programa que calcule e mostre na tela o resultado da soma entre 6 +
//8 + 10 + 12 + 14 + ... + 98 + 100.
Var

       Cont,S,N: Inteiro
Inicio

      Cont <-1
      S <-0

      Enquanto (Cont <= 5) faca
      Escreva ("Digite o", cont," o. valor: ")
      Leia (N)
      S <- S + N
      Cont <- Cont + 1
      Fimenquanto
      EscrevaL ("A Soma de todos os valores foi", S)
      


Fimalgoritmo