# Portugol
//Faça um programa que leia um número inteiro e mostre o seu antecessor e seu
//sucessor.
//Ex:
//Digite um número: 9
//O antecessor de 9 é 8
//O sucessor de 9 é 10

Algoritmo "MATEMATICA"

Var

   NU, ND, NT: inteiro

Inicio

      Escreva ("Digite um numero: ", NU)
      Leia (NU)
      ND <- NU - 1
      Escreval ("o antecessor de", NU, " ï¿½ " ,ND)
      NT <- NU + 1
      Escreva ("o sucessor de", NU, " ï¿½ " ,NT)



   

Fimalgoritmo