# Portugol

//Crie um algoritmo que leia um número real e mostre na tela o seu dobro e a
//sua terça parte.
//Ex:
//Digite um número: 3.5
//O dobro de 3.5 é 7.0
//A terça parte de 3.5 é 1.16666

Algoritmo "MATEMATICA"

Var

   NR, ND, NT: real

Inicio

      Escreva ("Digite um numero: ", NR)
      Leia (NR)
      ND <- NR * 2
      Escreval ("o dobro de ", NR, " ï¿½ " ,ND)
      NT <- NR / 3
      Escreva ("A terï¿½a parte de", NR, " ï¿½ " ,NT)



   

Fimalgoritmo