Algoritmo "semnome"

//Faça um algoritmo que leia quanto dinheiro uma pessoa tem na carteira (em R$)
//e mostre quantos dólares ela pode comprar. Considere US$1,00 = R$3,45.

Var

   L,A,Q,T: Real
   
Inicio

      Escreva ("largura: ")
      Leia (L)
      Escreva ("Altura: ")
      Leia (A)
      Q<- L*A
      EscrevaL ("A area a ser pintada é de", Q,"m²")
      T<- Q/2
      Escreva ("Será necessario", T, " litros de tinta")

Fimalgoritmo