# Portugol

//Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório
//entre eles.
//Ex:
//Digite um valor: 8
//Digite outro valor: 5
//A soma entre 8 e 5 é igual a 13.

Algoritmo "semnome"

Var

   A,B,C:inteiro

Inicio

      Escreva ("Digite um valor: ", A)
      Leia (A)
      Escreva ("Digite outro valor", B)
      Leia (B)
      C <- A+B
      Escreva("A soma de",A, " e",B, " ï¿½ igual a" ,C)



   

Fimalgoritmo